budget-buddy/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", RedirectView.as_view(url='/dashboard/', permanent=False)),
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("accounts/", include("user_profile.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", include("user_dashboard.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budget-buddy/user_profile/urls.py
"""User profile app URL."""
from django.urls import path

from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.UserProfileDetailView.as_view(), name="profile_detail"),
    path("profile/update/", views.UserProfileUpdateView.as_view(), name="profile_update"),
]

budget-buddy/users/urls.py
"""Accounts app URL Configuration."""
from django.urls import path

from users import views

app_name = "users"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
]

budget-buddy/users/models.py
"""Accounts models."""
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from users.managers import CustomUserManager


class CustomUser(AbstractUser):
    """Custom User class."""

    username = None
    email = models.EmailField(_("email address"), unique=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        """Return email as the object's string representation."""
        return self.email

budget-buddy/users/forms.py
"""Forms for accounts app."""
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from users.models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """Registration form."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = ("first_name", "last_name", "email", "password1", "password2")


class CustomUserChangeForm(UserChangeForm):
    """User profile change view."""

    class Meta:
        """Meta class."""

        model = CustomUser
        fields = ("email",)

budget-buddy/users/views.py
"""Accounts view."""
from django.urls import reverse_lazy
from django.views import generic

from users.forms import CustomUserCreationForm
from users.models import CustomUser


class SignUpView(generic.CreateView):
    """Sign up view for Users."""

    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = "generic_create_update_form.html"
    success_url = reverse_lazy("login")
    extra_context = {"title_text": "Sign Up", "button_text": "Register"}

budget-buddy/users/templates/base_generic.html
{# Load the tag library #}
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="us-en">
    <head>
        <meta charset="UTF-8" />
        <meta name="description" content="Budget-Buddy" />
        <meta name="keywords" content="HTML, CSS, JavaScript" />
        <meta name="author" content="Team 5" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}" />
        <title>Budget-Buddy</title>
        {# Load CSS and JavaScript #}
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {# Display django.contrib.messages as Bootstrap alerts #}
        {% bootstrap_messages %}
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <link href="{% static 'fontawesomefree/css/all.min.css' %}" rel="stylesheet" type="text/css" />
        {% block style %}
        <style>
            body {
                /* Background gradiant modifier */
                background: linear-gradient(to bottom right, #14c1da, #e9d962);
            }
        </style>
        {% endblock style %}
    </head>
    <body>
        {% include "navbar.html" %}
        <div class="container">
            <h1 class="text-center fw-bold mb-5">
                {% block title %}
                {% endblock title %}
            </h1>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

budget-buddy/users/templates/generic_create_update_form.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% block title %}
    {{ title_text }}
{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-4">
            <form method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {{ form.media }}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">{{ button_text }}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

budget-buddy/users/templates/generic_delete_confirm_form.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% block title %}
    {{ title_text }}
{% endblock title %}
{% block content %}
    <div class="d-flex justify-content-center">
        <div class="col-md-4">
            <form method="post">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                {{ form }}
                <input type="submit" value="Confirm" class="btn btn-danger">
            </form>
        </div>
    </div>
{% endblock content %}

budget-buddy/users/templates/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark justify-content-between">
    <div class="container">
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarsExampleDefault"
                aria-controls="navbarsExampleDefault"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'user_dash' %}">Dashboard</a>
        <div class="navbar-collapse collapse" id="#navbarsExampleDefault">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <div class="dropdown">
                        <a class="nav-link dropdown-toggle"
                           role="button"
                           data-toggle="dropdown"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <i class="fa-solid fa-user-shield"></i> {{ user.email }}
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a class="dropdown-item" href="{% url 'user_profile:profile_detail' %}">
                                    <i class="fa-solid fa-user-cog"></i> Profile
                                </a>
                            </li>
                            <li>
                                <div class="dropdown-divider"></div>
                            </li>
                            <li>
                                <form action="{% url 'logout' %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="dropdown-item">
                                        <i class="fa-solid fa-sign-out-alt"></i> Log out
                                    </button>
                                </form>
                            </li>
                        </ul>
                    </div>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">
                            <i class="fa-solid fa-sign-in"></i> Sign in
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">
                            <i class="fa-solid fa-user-edit"></i> Sign up
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block style %}
<style>
    .navbar {
        background-color: #161A1D;
        font-family: "Roboto", sans-serif;
    } 
   
</style>
{% endblock style %} 