budget-buddy/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", RedirectView.as_view(url='/dashboard/', permanent=False)),
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("accounts/", include("user_profile.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("dashboard/", include("user_dashboard.urls")),
    path("accounts/login/", auth_views.LoginView.as_view(), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

budget-buddy/user_profile/urls.py
"""User profile app URL."""
from django.urls import path

from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.UserProfileDetailView.as_view(), name="profile_detail"),
    path("profile/update/", views.UserProfileUpdateView.as_view(), name="profile_update"),
]

budget-buddy/users/urls.py
"""Accounts app URL Configuration."""
from django.urls import path

from users import views

app_name = "users"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
]

budget-buddy/user_profile/models.py
"""User profile model."""
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from user_dashboard.models import UserDashboard, Category

from users.models import CustomUser


class UserProfile(models.Model):
    """UserProfile model class."""

    class Gender(models.IntegerChoices):
        """Gender choice class."""

        FEMALE = 1
        MALE = 2
        OTHER = 3

    custom_user = models.OneToOneField("users.CustomUser", on_delete=models.CASCADE)
    gender = models.IntegerField(choices=Gender.choices, default=Gender.FEMALE)
    age = models.IntegerField(default=1)
    picture = models.ImageField(upload_to="user_profile/profile_pictures/", blank=True)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


@receiver(post_save, sender=CustomUser)
def create_profile(sender, instance, created, **kwargs):
    """Create an object of UserProfile when a user CustomUser object is created."""
    if sender and created:
        UserProfile.objects.create(custom_user=instance)
        UserDashboard.objects.create(custom_user=instance)

        for c in ['Other', 'Groceries', 'Bills', 'Entertainment', 'Loans']:
            Category.objects.create(user=instance, name=c)

post_save.connect(create_profile, sender=CustomUser)

budget-buddy/user_profile/forms.py
"""User Profile Forms."""
from django import forms

from . import models

class UserProfileUpdateForm(forms.ModelForm):
    """User profile change view."""

    first_name = forms.CharField(max_length=32)
    last_name = forms.CharField(max_length=32)

    class Meta:
        """Meta class."""

        model = models.UserProfile
        fields = ["first_name", "last_name", "gender", "age"]

budget-buddy/user_profile/views.py
"""User profile view."""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from . import forms, mixins, models


# Create your views here.
class UserProfileDetailView(generic.DetailView):
    """Profile detail view."""
    model = models.UserProfile
    template_name = "user_profile/userprofile_detail.html"
    slug_field = None
    slug_url_kwarg = ""

    def get_object(self, queryset=None):
        """Get the UserProfile object for the current user."""
        user_profile, created = models.UserProfile.objects.get_or_create(custom_user=self.request.user)
        return user_profile

    def dispatch(self, request, *args, **kwargs):
        """Check if the user has a UserProfile, if not, create one."""
        user_profile = self.get_object()
        if not user_profile:
            return HttpResponseRedirect(reverse('user_profile:create_profile'))
        return super().dispatch(request, *args, **kwargs)


class UserProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    """Profile update view."""

    model = models.UserProfile
    form_class = forms.UserProfileUpdateForm
    success_url = reverse_lazy("user_profile:profile_detail")
    template_name = "generic_create_update_form.html"
    extra_context = {"title_text": "Update Profile", "button_text": "Update"}

    def get_object(self, queryset=None):
        """Get the `UserProfile` object the current logged in user."""
        return self.model.objects.filter(custom_user=self.request.user).first()

    def get_context_data(self, **kwargs):
        """Add additional fields to the form."""
        context = super().get_context_data(**kwargs)

        user_profile = self.request.user.userprofile

        initial = {
            "first_name": self.request.user.first_name,
            "last_name": self.request.user.last_name,
        }

        context["form"] = forms.UserProfileUpdateForm(instance=user_profile, initial=initial)

        return context

    def form_valid(self, form):
        """Set custom_user Field of the current object as the current user."""
        user_profile = form.save(commit=False)
        user_profile.custom_user = self.request.user

        custom_user = self.request.user
        custom_user.first_name = form.cleaned_data["first_name"]
        custom_user.last_name = form.cleaned_data["last_name"]
        user_profile.save()
        custom_user.save()

        return super().form_valid(form)

budget-buddy/user_profile/templates/user_profile/userprofile_detail.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
    User Profile
{% endblock title %}
{% block content %}
    <style>
        .profile-card {
            background-color: rgba(71, 71, 71, 0.404);
            border: 1px solid rgba(0, 0, 0, 0.125);
        }
    </style>

    <div class="container mt-5">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="card profile-card">
                    <div class="card-header bg-primary text-white">
                        <h5 class="card-title mb-0">Profile Details</h5>
                    </div>
                    <div class="card-body profile-details" style="color: rgb(0, 0, 0);">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item border-0 border-top" style="color: white;">First Name: {{ user.first_name }}</li>
                            <li class="list-group-item border-0" style="color: white;">Last Name: {{ user.last_name }}</li>
                            <li class="list-group-item border-0" style="color: white;">Age: {{ user.userprofile.age }}</li>
                            <li class="list-group-item border-0 border-bottom" style="color: white;">Gender: {{ user.userprofile.get_gender_display }}</li>
                        </ul>
                    </div>
                    <div class="card-footer text-muted text-center">
                        <a href="{% url 'user_profile:profile_update' %}" class="btn btn-primary">
                            <i class="fas fa-edit me-1"></i> Update Profile
                        </a>
                        <a href="{% url 'password_change' %}" class="btn btn-warning">
                            <i class="fas fa-user-cog me-1"></i> Change Password
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
{% endblock content %}

budget-buddy/user_profile/templates/user_profile/userprofile_update.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}
    Welcome {{ user }}
{% endblock title %}
{% block content %}
    <div class="row align-items-md-stretch py-4">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <h1 class="text-center mb-4">Edit Profile</h1>
            <form action="{% url 'user_profile:profile_update' %}"
                  method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary justify-center">Update</button>
                </div>
            </form>
        </div>
        <div class="col-md-3"></div>
    </div>
{% endblock content %}